id: db54b41daafd433e8be4b45425d136ea
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_86-The_Question_of_Maitreya_on_the_Eight_Qualities-v1
  language: en
  author: ''
  volume: {}
